### ISSUE TITLE
Blog Post: SRVi

### ISSUE THREAD

**Issue by ajhager** [gopherjs/gopherjs.github.io#4]
```
What is it?
Why would you use it?
How does it work?
Step by Step example project.
How would you create your own custom tool using the compiler API? (brief overview with a follow up post later)
```

**Comment by shurcooL** [comment]
Now that `gopherjs serve` command has become more featureful and capable (after pulling the missing features from SRVi and gopherjs_serve_html), is this issue still relevant or can it be closed?

**Comment by ajhager** [comment]
Unless you think there a blog post in the functionality of `gopherjs serve`, this can probably be closed.

**Comment by shurcooL** [comment]
It would be great to cover `gopherjs serve` indeed.

**Comment by shurcooL** [comment]
It doesn't look like there's anyone in the GopherJS community capable of writing a blog post about `gopherjs serve` since we can't even resolve https://github.com/gopherjs/gopherjs/issues/268 after many months, which is a much smaller scope, yet equally important. I'm going to take that item next.

I'll close this to since it appears to be out of scope for the current team, in order to have a more realistic scope set in sight.

Anyone can feel free to reopen if they believe it's worth keeping this issue open.
