### ISSUE TITLE
Playground: Gist support

### ISSUE THREAD

**Issue by ajhager** [gopherjs/gopherjs.github.io#6]
We do not support sharing directly from the playground, since it is all client side. Adding the ability to load Github gists or Golang playground code by id should help fill in that gap.

We also might be able to add a route in angularjs like /playground/[gist-id] that automatically loads the code from the gist with that id.

**Comment by shurcooL** [comment]
Ping @neelance. I'd like to make progress on this issue.

Again, I still considering all factors, we have a pretty decent chance of getting a "yes" response.

Would you like to post the question @neelance, or would you prefer I do it on your behalf?

**Comment by neelance** [comment]
Yes, please go ahead.

**Comment by shurcooL** [comment]
I've done so here:

https://groups.google.com/forum/#!topic/golang-dev/zSK8WhhiYDE

**Comment by shurcooL** [comment]
Well, we have partial success!

https://groups.google.com/d/msg/golang-dev/zSK8WhhiYDE/tub0B5svp9wJ

@adg said we're okay to load snippets from Go playground, but we shouldn't store new ones there.

I guess they're not yet very familiar with GopherJS and the kind of programs/snippets it's likely to compile, so they don't want those unknown programs polluting the namespace, which is fair (and I'm sure the decision can be revisited in the future once the unknowns become more known).

Since we will definitely need a backend to store the snippets, there's not much point int asking for CORS for loading, as the backend can simply forward them along.

It seems that we'll need a simple backend for storing GopherJS playground Go code snippets. It doesn't seem very hard to create. I can volunteer to do it.

The main requirements would be:

- generate/reuse same IDs for existing inputs,
- try to avoid collisions between IDs coming from Go playground with ones we create ourselves.

Am I missing anything?

**Comment by shurcooL** [comment]
Separately, we need to decide on a frontend URL scheme. How about:

http://play.golang.org/p/D9L6MbPfE4
http://gopherjs.org/play/?p=D9L6MbPfE4

(Since the playground is served as part of a static website, as far as I know, it has to be a query parameter. Correct?)

**Comment by shurcooL** [comment]
Two alternative schemes:

http://gopherjs.org/play/?p=D9L6MbPfE4
http://gopherjs.org/play/#/D9L6MbPfE4

Any preference? /cc @ajhager

**Comment by shurcooL** [comment]
I'm working on this now (@ajhager, feel free to assign this issue to me; I can't because I don't have push rights for this repo), quick question for @ajhager or @neelance:

Is it okay if I use [`honnef.co/go/js/dom`](https://godoc.org/honnef.co/go/js/dom) and [`honnef.co/go/js/xhr`](https://godoc.org/honnef.co/go/js/xhr`) packages in the `playground.go` source code? Right now I'm not using them for consistency, but it would be nice if I could.

**Comment by shurcooL** [comment]
Ok, I have this working and pretty close to done. The backend component is almost done, just needs final review. The frontend components works, but needs to be cleaned up and use AngularJS better.

The PR for the backend component ready for final review, see https://github.com/gopherjs/snippet-store/pull/1.

The PR for the frontend change is very rough, and has lots of TODOs and code cleanup remaining, but just to get the process started, see PR https://github.com/gopherjs/gopherjs.github.io/pull/11.

I've setup a temporary copy of the playground where you can test out the snippet loading/saving, etc. The compiling doesn't work because I didn't update the compiler files but my `gopherjs` is newer. Compiling is unrelated to snippet loading/sharing so it doesn't matter.

http://dmitri.shuralyov.com/temp/playground/index.html
http://dmitri.shuralyov.com/temp/playground/index.html#/Fi6ixjyYo_ (snippet from local storage)
http://dmitri.shuralyov.com/temp/playground/index.html#/D9L6MbPfE4 (snippet from Go Playground)

There are some minor usability bugs to iron out with the frontend (see PR for details), but it should mostly work. Let me know what you think!

**Comment by neelance** [comment]
@shurcooL I'll give you push rights to this repo.
@dominikh I've seen that you have already done some code review. Thx.
@shurcooL @dominikh @ajhager Is it okay for you guys if I leave this up to you? I don't have so much time and I would like to spend it on improving GopherJS itself. I'm sure you'll come up with a great solution. One suggestion anyway: We can use https://www.heroku.com/ for running the server. Their smallest usage tier is free and it should be enough. I have used https://github.com/kr/heroku-buildpack-go before and it worked really well.

**Comment by neelance** [comment]
@shurcooL 
> Is it okay if I use honnef.co/go/js/dom and honnef.co/go/js/xhr packages in the playground.go source code? Right now I'm not using them because the package doesn't already import them, but it would be nice if I could.

I think it should be okay.

**Comment by shurcooL** [comment]
This is done and deployed. I've immediately found a minor issue #14, and fixed it in #15.

http://gopherjs.org/play/#/Myqj0bQVev is the first official GopherJS Playground snippet. Feel free to share, and please report any issues if you find any! We want the experience to be nothing short of delightful.
