### ISSUE TITLE
New logo and icons

### ISSUE THREAD

**Issue by ajhager** [gopherjs/gopherjs.github.io#7]
See gopherjs/gopherjs-book#10.

**Comment by shurcooL** [comment]
I mentioned to @neelance that I wanted to open an issue about this, but this is already an open issue.

> *me:* by the way, I plan to open an issue on gopherjs.github.io repo - "Improving GopherJS website logo and image". I'd like to see the gopherjs.org website to look more friendly and "cute" like golang.org, and I want to find a way for us to get that Gopher on a Surfboard image, and use it for the gopherjs organization and twitter account.
> *Richard:* +100

We have a draft for the proposed logo by Jason Aten, a surfing Gopher, available at https://groups.google.com/forum/#!topic/gopherjs/7X0EUZCaTFs. I think we all agree it is really cool and the way to go. I've attached a copy below:

![gopherjs_logo](https://cloud.githubusercontent.com/assets/1924134/5772391/d6f3f5f6-9d06-11e4-9757-6d5921930942.jpg)

> It's fine to use the gopher as long as you give Renee French, the original designer (and Rob Pike's spouse), credit.

I think we need to clean it up a bit and make it more presentable for use as a GitHub and Twitter avatars, and as a website logo.

Just posting here to show my renewed interest in making progress on this issue. :)

**Comment by shurcooL** [comment]
One thought I have after seeing the draft logo up close again:

I think it would make sense to remove the letters `JS` and perhaps just have a little wave or the rest of the surfboard in its place. The reasons:

- We want the logo to _represent_ something with imagery, not spell it out. The Gopher represents Go but it doesn't have Go physically written. IMO the surfboard does a good job at representing JavaScript and frontend in general.
- At smaller logo sizes (think Twitter/GitHub logo), the text would be too small and unreadable I think.

**Comment by neelance** [comment]
I would like to have the "JS" written on the bottom side of the surfboard itself, just because it's so cool to see the Gopher ride the "JS" board.

**Comment by shurcooL** [comment]
Hi everyone,

I didn't want to say anything until my attempt was successful, but some time ago I asked Renee French (through Francesc Campoy who was kind enough to ask on my behalf) if she'd be interested in drawing a surfing gopher like the one above that we could use. I figured there was a tiny non-zero chance she'd want to do that, so it was worth a shot.

Unfortunately, that didn't work out. It seems this issue got stale and no one is making progress on it, so I had no choice but to take matters into my own hands.

I am no artist, I can't draw well, but I tried my best. After all, Jason Aten already drew a very nice mockup on paper and I thought it should be doable to turn it into something usable as an avatar/logo.

I cleaned up the background to be white, and fixed up various details here and there... and I think the end result is passable... (The [competition](https://cloud.githubusercontent.com/assets/1924134/7929872/cec20018-08b7-11e5-8200-fd9c7b372677.png) is not very strong.) This is a 512x512 PNG with transparency.

[![gopherjs logo 512 alpha](https://cloud.githubusercontent.com/assets/1924134/7929862/ada8ff08-08b7-11e5-8011-d758127d1292.png)<br><br>https://cloud.githubusercontent.com/assets/1924134/7929862/ada8ff08-08b7-11e5-8011-d758127d1292.png](https://cloud.githubusercontent.com/assets/1924134/7929862/ada8ff08-08b7-11e5-8011-d758127d1292.png)

Of course, all credit goes to Renee French for the original gopher design and Jason Aten for the picture he drew and shared.

I hope this is good enough to be usable as an avatar for the [gopherjs organization](https://github.com/gopherjs) and [@GopherJS](https://twitter.com/gopherjs) twitter account, both of which currently feature stock avatars. What do you think?

Here's a preview of what it could look like, I tried it out on the goxjs org. https://github.com/goxjs (I personally like it a lot.)

**Comment by shurcooL** [comment]
@egonelbre has created some cool spin-offs at https://github.com/egonelbre/gophers:

[![](https://raw.githubusercontent.com/egonelbre/gophers/master/sketch/surfing-js.jpg)](https://github.com/egonelbre/gophers/blob/master/sketch/surfing-js.jpg)

[![](https://raw.githubusercontent.com/egonelbre/gophers/master/png/surfing-js.png)](https://github.com/egonelbre/gophers/blob/master/png/surfing-js.png)

I think the second one could look pretty cool on the website, e.g., if @egonelbre is okay with that.

![image](https://cloud.githubusercontent.com/assets/1924134/8018344/81a80bde-0bcc-11e5-977a-1faf95c09295.png)

Although it would look nicer if the website theme is changed to a lighter, friendlier one (like golang.org).

**Comment by egonelbre** [comment]
>  if @egonelbre is okay with that.

The Gophers in https://github.com/egonelbre/gophers are CC0 - so no need to ask me when using/modifying them. https://creativecommons.org/publicdomain/zero/1.0/. Even attribution isn't necessary since, although it's not prohibited either :).

For Lighter themed website, I would make the Gopher sit on a box:

With blue base and rotated slightly:
![2015-06-06 08_04_31-_surfing-js svg - inkscape](https://cloud.githubusercontent.com/assets/192964/8018399/bd5fd926-0c22-11e5-8448-04221b8ca79b.png)

Or with a different color base:
![2015-06-06 08_06_32-_surfing-js svg - inkscape](https://cloud.githubusercontent.com/assets/192964/8018405/fd5436c6-0c22-11e5-9646-6c5d3c966d00.png)

For avatar or github logo, you can try cropping it e.g.
![gopher-js-cropped](https://cloud.githubusercontent.com/assets/192964/8018431/1a8121e0-0c24-11e5-89a4-644c606d6fa1.png)

For icon you could crop and reposition text:
![mini](https://cloud.githubusercontent.com/assets/192964/8018446/9c6a2594-0c24-11e5-8445-5ffff497f6b8.png)

Or remove the big board and use the shadow as the board:
![mini2](https://cloud.githubusercontent.com/assets/192964/8018456/06a33504-0c25-11e5-98ad-b4341f2320ef.png)

**Comment by rusco** [comment]
Some cents from my side:

The "official" JS logo, used already in a lot projects is here:

https://camo.githubusercontent.com/eb464a60a4a47f8b600aa71bfbc6aff3fe5c5392/68747470733a2f2f7261772e6769746875622e636f6d2f766f6f646f6f74696b69676f642f6c6f676f2e6a732f6d61737465722f6a732e706e67

Here are some modifications:

https://github.com/voodootikigod/logo.js/blob/master/registry.md

My proposals are 
1. to align the font of the "JS" letters with the "official" JS logo to facilitate association
2. to confine the black background color of the main GopherJS page to the menu and/or the footer (black is probably the most controversial background color, due to psychological and other reasons). 

I'm not a designer at all, so I can not help with designing things. Please keep up your good job !

**Comment by egonelbre** [comment]
With JS font, blue background
![bb](https://cloud.githubusercontent.com/assets/192964/8020554/c0e4fbea-0c85-11e5-8ba9-75404508b4c4.png)
With JS yellow background:
![yb](https://cloud.githubusercontent.com/assets/192964/8020553/c0e38026-0c85-11e5-982a-fd5617019f70.png)
For comparison:
![ob](https://cloud.githubusercontent.com/assets/192964/8020565/3247db7c-0c86-11e5-8bb8-65b77d48405c.png)

**Comment by shurcooL** [comment]
I think this issue is resolved and can be closed now. Both the GitHub organization and Twitter now have a nicer logo than the previous square blocks.

https://github.com/gopherjs
https://twitter.com/gopherjs

Thank you so much to everyone who made this possible!

P.S. For increased variety, I've used @egonelbre's excellent variation for [goxjs](https://github.com/goxjs) organization.

**Comment by shurcooL** [comment]
@dwhitena has drawn and shared this awesome take on the surfing gopher!

![gopherjs by daniel whitenack](https://cloud.githubusercontent.com/assets/1924134/17153672/ada6e3c8-534b-11e6-9766-99ae30754f08.png)
